name: landslide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animate_do: ^3.1.2
  showcaseview: ^3.0.0
  # file_picker: ^5.1.0
  flutter_native_splash: ^2.2.4
  animated_splash_screen: ^1.0.0
  dio: ^5.0.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ICON.png

flutter_native_splash:
  color: "#004d40"
  image: assets/ICON.png
  android: true
  ios: true
